import os
import datetime
from pathlib import Path
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.config.settings import settings
from app.utils.file_utils import is_safe_path
from app.utils.logger import get_logger

logger = get_logger(__name__)

class DocumentGenerationError(Exception):
    pass

class DocumentService:
    @staticmethod
    def generate_pdf(
        document_id: str,
        document_type: str,
        data: Dict[str, Any],
        output_dir: Optional[str] = None
    ) -> str:
        """
        Generate a professional structured PDF document populated with extracted fields.
        Saves output in data/output/ with path-traversal safety.
        """
        out_dir = output_dir or settings.OUTPUT_DIR
        os.makedirs(out_dir, exist_ok=True)

        clean_doc_type = document_type.replace(" ", "_").lower()
        filename = f"completed_{clean_doc_type}_{document_id}.pdf"
        target_path = os.path.join(out_dir, filename)

        if not is_safe_path(out_dir, target_path):
            raise DocumentGenerationError("Path traversal detected in output file path.")

        try:
            doc = SimpleDocTemplate(
                target_path,
                pagesize=letter,
                rightMargin=40,
                leftMargin=40,
                topMargin=40,
                bottomMargin=40
            )

            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'DocTitle',
                parent=styles['Heading1'],
                fontSize=20,
                leading=24,
                textColor=colors.HexColor("#1e293b"),
                spaceAfter=10
            )
            subtitle_style = ParagraphStyle(
                'DocSubtitle',
                parent=styles['Normal'],
                fontSize=10,
                textColor=colors.HexColor("#64748b"),
                spaceAfter=15
            )
            cell_bold = ParagraphStyle(
                'CellBold',
                parent=styles['Normal'],
                fontSize=10,
                leading=13,
                fontName="Helvetica-Bold",
                textColor=colors.HexColor("#0f172a")
            )
            cell_normal = ParagraphStyle(
                'CellNormal',
                parent=styles['Normal'],
                fontSize=10,
                leading=13,
                textColor=colors.HexColor("#334155")
            )

            elements = []

            # Header / Title
            title_text = f"Automated Document Summary: {document_type.replace('_', ' ').title()}"
            elements.append(Paragraph(title_text, title_style))
            
            created_str = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
            subtitle_text = f"Document ID: <b>{document_id}</b> &nbsp;|&nbsp; Generated: {created_str} &nbsp;|&nbsp; Status: <b>VERIFIED</b>"
            elements.append(Paragraph(subtitle_text, subtitle_style))
            elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=15))

            # Table of Fields
            table_data = [[
                Paragraph("Field Name", cell_bold),
                Paragraph("Extracted & Verified Value", cell_bold)
            ]]

            for k, v in data.items():
                field_label = k.replace("_", " ").title()
                val_str = str(v) if v is not None else "N/A"
                table_data.append([
                    Paragraph(field_label, cell_bold),
                    Paragraph(val_str, cell_normal)
                ])

            t = Table(table_data, colWidths=[180, 350])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ]))

            elements.append(t)
            elements.append(Spacer(1, 20))

            # Verification stamp note
            footer_text = "<i>This document was automatically extracted, verified against business rules, and generated by the Agentic Document Automation System.</i>"
            elements.append(Paragraph(footer_text, subtitle_style))

            doc.build(elements)
            logger.info(f"Successfully generated completed document at {target_path}")
            return target_path

        except Exception as e:
            logger.error(f"Failed to generate output PDF: {e}")
            raise DocumentGenerationError(f"PDF creation failed: {str(e)}")

document_service = DocumentService()
